### ISSUE TITLE
Use this analyzer for a live data tracing

### ISSUE THREAD

**Issue by Arfaoui-Mahdi** [matthiasbock/pcan-view-trace-error-analyzer#1]
Hi, thanks for this project, I was wondering if I could use your solution to take data generated by Pcan-view (picture below)of the traced data and use in another program (for example save those result in a txt file ...)

![image](https://user-images.githubusercontent.com/53017181/120820947-4aa2b000-c555-11eb-8eba-94552215a3a0.png)

Thanks

**Comment by matthiasbock** [comment]
Hi.
Unfortunately, your image is very small. I can't read anything.
Also, I don't understand your question. What specifically are you trying to do?
Regards

**Comment by matthiasbock** [comment]
Closing the issue, since requested additional information was not provided. Feel free to re-open, if it's still relevant.
